spring:
  cloud:
    gateway:
      routes:
      - id: golden_route
        uri: http://localhost:8081
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1
        - AddRequestHeader=GoldenCustomer,true
      - id: common_route
        uri: http://localhost:8081
        predicates:
        - Path=/another/**
        - name: GoldenCustomer
          args:
            golden: false
            customerIdCookie: customerId
        filters:
        - StripPrefix=0
        - AddRequestHeader=GoldenCustomer,false
        
              
        